// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Yv2dzHOxht8IXbExjL7Fz6pPeBP0d50',
    appId: '1:524638568840:android:aad37e57a6a2d600f0fa3d',
    messagingSenderId: '524638568840',
    projectId: 'presensi-sekolah-50f43',
    storageBucket: 'presensi-sekolah-50f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmipHAszPPcOkNKrVMYos-diMcGvpZQE',
    appId: '1:524638568840:ios:ce900b7df41a1e9ff0fa3d',
    messagingSenderId: '524638568840',
    projectId: 'presensi-sekolah-50f43',
    storageBucket: 'presensi-sekolah-50f43.firebasestorage.app',
    androidClientId: '524638568840-ebn1sal9u9ng2a1id2h7dve2unggdg0f.apps.googleusercontent.com',
    iosClientId: '524638568840-um9blq9k3efs16drkb909ji98cd8hoda.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkPresensiSma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmipHAszPPcOkNKrVMYos-diMcGvpZQE',
    appId: '1:524638568840:ios:ce900b7df41a1e9ff0fa3d',
    messagingSenderId: '524638568840',
    projectId: 'presensi-sekolah-50f43',
    storageBucket: 'presensi-sekolah-50f43.firebasestorage.app',
    androidClientId: '524638568840-ebn1sal9u9ng2a1id2h7dve2unggdg0f.apps.googleusercontent.com',
    iosClientId: '524638568840-um9blq9k3efs16drkb909ji98cd8hoda.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkPresensiSma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYM0qh0hBHhJbQP3FfWD6KUsCFOegPYg',
    appId: '1:524638568840:web:6c9155608b6d1371f0fa3d',
    messagingSenderId: '524638568840',
    projectId: 'presensi-sekolah-50f43',
    authDomain: 'presensi-sekolah-50f43.firebaseapp.com',
    storageBucket: 'presensi-sekolah-50f43.firebasestorage.app',
    measurementId: 'G-TQ8LNHC685',
  );

}